[package]
name = "script"
version = "0.0.1"
authors = []
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
turing-api = "=0.0.4"

[profile.release]
# optimize for small code size
opt-level = "s"
